export * from './get-about-company'
export * from './get-welcome-to-my-page'
export * from './get-contact'
export * from './get-prices-cards'
export * from './get-prices-info'
export * from './post-send-email'
