export const ABOUT_COMPANY = 'about-company'
export const WELCOME_TO_MY_PAGE = 'welcome-to-my-page'
export const CONTACT = 'contact'
export const PRICES_CARDS = 'prices-cards'
export const PRICES_INFO = 'prices-info'
